import Head from "next/head";
import Link from "next/link";
import styles from "@/styles/Home.module.css";
import Divider from "components/Divider/Divider";
import HomeBarChart from "components/HomePageComps/HomeBarChart";
import HomeExperts from "components/HomePageComps/HomeExperts";
import HomePosts from "components/HomePageComps/HomePosts";
import HomPartners from "components/HomePageComps/HomPartners";
import HomeText from "components/HomePageComps/HomeText";

export default function Home() {
  return (
    <>
      <Head>
        <title>Index of Reforms</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.mainAbout}>
        <Divider heading="Індекс" gray={true} openable={false} single={false} />
        <HomeBarChart />
        <HomeText />
        <div className="my-0 mx-auto pt-4">
          <Link href="/" className="hover:text-red-600 text-[14px]">
            Інтерактивний графік
          </Link>
        </div>
        <Divider
          heading="Наші експерти"
          gray={true}
          openable={false}
          single={false}
        />
        <HomeExperts />
        <Divider
          heading="Індекс реформ Вокс Україна"
          gray={true}
          openable={false}
          single={false}
        />
        <HomePosts />
        {/* <Divider
          heading="Наші партнери"
          gray={true}
          openable={false}
          single={false}
        />
        <HomPartners /> */}
      </main>
    </>
  );
}
