import Head from "next/head";
import BarChart from "../../components/BarChart/BarChart";
import StackedBarChart from "components/BarChart/StackedBarChart";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>The War Laws</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <BarChart />
        {/* <StackedBarChart /> */}
      </main>
    </>
  );
}
