import Head from "next/head";
import styles from "@/styles/Home.module.css";
import useSWR from "swr";
import { fetcher } from "lib/fetcher";

export default function Method() {
  const { data, error } = useSWR(
    `https://vox-imore.ra-devs.tech/api/pages?lang=ua`,
    fetcher,
    {
      revalidateIfStale: false,
      revalidateOnFocus: false,
      revalidateOnReconnect: false,
    }
  );
  const pageRender =
    data &&
    data.data.map((page, i) => {
      if (page.id == 2) {
        return (
          <div key={i} className="mb-4">
            <h2 className="text-xl mb-8">{page.title}</h2>
            <p dangerouslySetInnerHTML={{ __html: page.content }} />
          </div>
        );
      }
    });
  return (
    <>
      <Head>
        <title>Methodology</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.mainAboutPage}>{pageRender}</main>
    </>
  );
}
